language: node_js
dist: trusty
sudo: required
node_js:
- node
cache:
  directories:
  - "/home/travis/build/InstantCodee/TypeOS/node_modules"
notifications:
  on_success: always
  email: false
  slack:
    rooms:
      secure: nzJ22I4987N4284+w2xJ+IB78JHNXRVjq87Dd3V2gCx6HAc3Vyu+8vcQeUUpRQoINzD5pettwXzcvSCvo5IjbYoWtEqmI/tR8C5E08UZg3CYriGfyPf7rwAYmZOboNfTJAgtMe4XJZ/ygORHE5aS16T8O/foWmWWe2H2XTtd8Iby9BeTB2ZIQZ7MdUvU/oUp2K787jF7Zucq2MM5JtCFbehuv+jECpWR8u5QsTUb9i0KO2R/8J2EnHvEXJgTXJB5dj5XuVgMUf03PPj6yDdaSXS/+R2HrxuC1DBut9Y38Y8zOAfYxnkukMdlSOil4b8+biVjIkAuy7qRMTp6+b+EQ8XLBTVTZ+6CWwDv3Y3AmPB4mvzRsHtsDv/JkgF1b8BV0gkmdvS4eYyMjaa9tcr8tiE3a7WFNcx8T6aQQCaGIZFvvcU8nhvzHTU6GRcNpo2rEFZL3Ms4dHyevM2E2Dp5QJCon5UKjZKf05+UO4ozZuRrL6phtL0Grkv/eC5MIgeZlVE1HlC/DIcwEOEZTNlh1ijJvOiKGVHZXGi8pr30mQ/Bu8tF4Ax0PevazpV+xb6DUZ5AAAI2tbXC6U0mCjRZ8PExoi1bxwYBk6hTka9Osekm+6b+otnXehg6NFQmCzD/+08J03F9MW/vmD9WHOJg+1wz9YNHjyWmsN0ZIJe9q84=
git:
  depth: false
install:
- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get install -y nodejs
jobs:
  include:
  - stage: tests
    name: Unit Tests
    script: npm test
